# -*- coding: utf-8 -*-
"""yolov8_pothole.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e2Ef8dRXDMeQyz3PT6uKvOv_mgSC9W5O
"""

!wget https://www.dropbox.com/s/qvglw8pqo16769f/pothole_dataset_v8.zip?dl=1 -O pothole_dataset_v8.zip

!unzip pothole_dataset_v8.zip

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

!pip install clearml

!clearml-init

!yolo task=detect mode=train model=yolov8n.pt imgsz=640 data=/content/pothole_dataset_v8/pothole.yaml epochs=10 batch=8 name=yolov8_custom



